version: "3.7"
services:
  web-server:
    image: wordpress:5.7.2-apache
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${db_host}
      WORDPRESS_DB_USER: ${db_user}
      WORDPRESS_DB_PASSWORD: ${db_pass}
      WORDPRESS_DB_NAME: ${db_name}
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${db_name}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_pass}
      MYSQL_ROOT_PASSWORD: ${db_root_pass}
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: ${db_host}
      PMA_USER: root
      PMA_PASSWORD: ${db_root_pass}
    ports:
      - "5000:80"

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
    volumes: 
        - "./nginx/default/default.conf:/etc/nginx/conf.d/default.conf"

volumes:
  db:
  wordpress: